exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

# base url for specification source links (added during website build)
#github_specs_base_url: "https://github.com/lfe-cds/CDS-Registration/blob/main/specifications"
