name: Website Build
on:
  push:
    branches:
      - main
jobs:
  WebsiteBuild:
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/main-branch/website/Gemfile

    permissions:
      contents: write

    steps:

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          path: main-branch

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages-branch

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Replace placeholder files with original files
        run: |
          # copy original files to website directory
          cp \
            ${{ github.workspace }}/main-branch/specifications/cds-wg1-01/dev/cds-wg1-01-dev.md \
            ${{ github.workspace }}/main-branch/website/_includes/spec_copies/placeholder_cds-wg1-01-dev.md

          cp \
            ${{ github.workspace }}/main-branch/specifications/cds-wg1-02/dev/cds-wg1-02-dev.md \
            ${{ github.workspace }}/main-branch/website/_includes/spec_copies/placeholder_cds-wg1-02-dev.md

          # update specifications source base url with current repo and branch
          echo "github_specs_base_url: \"https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/specifications\"" \
            >> ${{ github.workspace }}/main-branch/website/_config.yml
          
          # default base url is root of domain
          echo "baseurl: /" \
            >> ${{ github.workspace }}/main-branch/website/_config.yml

      - name: Non-production builds use Github Page's default base url (/CDS-Registration/)
        if: ${{ github.repository != 'lfe-cds/CDS-Registration' }}
        run: |
          sed -i \
            's|baseurl: \/|baseurl: /CDS-Registration/|g' \
            ${{ github.workspace }}/main-branch/website/_config.yml

      - name: Build static website
        run: |
          cd ${{ github.workspace }}/main-branch/website
          bundle exec jekyll build -d ${{ github.workspace }}/gh-pages-branch

      - name: Set production domain
        if: ${{ github.repository == 'lfe-cds/CDS-Registration' }}
        run: |
          echo -n "cds-registration.lfenergy.org" > ${{ github.workspace }}/gh-pages-branch/CNAME

      - name: Push static site to gh-pages branch
        run: |
          cd ${{ github.workspace }}/gh-pages-branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          # only commit and push if there's actually things commit
          if [ $(git status --short | wc -l) -ne 0 ]; then
              echo "Pushing website changes to gh-pages..."
              git add -A
              git commit -m "[bot] Github Pages build"
              git push
          else
              echo "No changes on website"
          fi
